// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/grocery/AIInsightsScreen.tsx": () => import("../components/mockups/grocery/AIInsightsScreen.tsx"),
  "./components/mockups/grocery/DetailScreen.tsx": () => import("../components/mockups/grocery/DetailScreen.tsx"),
  "./components/mockups/grocery/HomeScreen.tsx": () => import("../components/mockups/grocery/HomeScreen.tsx")
};
